import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import CartDrawer from "@/components/CartDrawer";
import Header from "@/components/Header";
import { getAuth } from "@/lib/auth/get-auth";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth = await getAuth();

  return (
    <html lang="en">
      <AuthProvider value={auth}>
        <CartProvider>
          <body className="bg-base overflow-x-hidden">
            <Header />
            <CartDrawer />
            {children}
          </body>
        </CartProvider>
      </AuthProvider>
    </html>
  );
}
